### PR TITLE
Fix nuisance error if locale is not supported

### PR DESCRIPTION
**Pull request by dozius**
Fixes issue #2.

[winsplit-revolution_10.0.1_x64-rc1.zip](https://github.com/dozius/winsplit-revolution/files/4465088/winsplit-revolution_10.0.1_x64-rc1.zip)

### CODE REVIEW

**Comment by dozius** [comment]
@Wiethoofd, please try the release candidate attached to this PR to see if it solves your issue. Thanks!

**Comment by Wiethoofd** [comment]
No more error.

Checked with removing the settings .xml files in `%appdata%\Winsplit Revolution` and removing all the ones in the folder with the executables (if existed/generated).

Somehow the 10.0.0.0 version also stopped throwing the error, but that might also have been because the language got set to Dutch.

**Comment by dozius** [comment]
Great. Thanks for testing.

**Comment by jollyrishi** [comment]
@dozius I'm using WinSplit 11.04 on windows 7 os. Unable to understand how to apply your attached files to my setup since yours is version 10.0 and doesn't work here.

I want to get rid of the error 'Unable to set default language". My system language is set to English (India), and i don't wish to change that. Any tweak that can be suggested to be done to the winsplit internal files to either link to local system language or just remove the error?

Thanks alot. You're the only person on the internet who's probably resolved this i guess :)!

**Comment by dozius** [comment]
This fix is only viable for open source forks of winsplit, like this one. It requires changes in the source code as described by this pull request.

In the future, please open a new issue or message me directly rather than clutter old issues or pull requests with unrelated comments. Thanks!

**Pull request merged**
